# Generated by Django 4.2.29 on 2026-04-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_espece', models.CharField(max_length=50)),
                ('besoins_specifiques', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('date_naissance_estimee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('DISP', 'Disponible'), ('SOIN', 'En soin'), ('ADOP', 'Adopté'), ('FAMILLE', "En famille d'accueil")], default='DISP', max_length=10)),
                ('date_arrivee', models.DateField(auto_now_add=True)),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('compatibilite_chats', models.BooleanField(default=False)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaux.espece')),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_adoptant', models.CharField(max_length=200)),
                ('date_adoption', models.DateField(auto_now_add=True)),
                ('frais_participation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animaux.animal')),
            ],
        ),
    ]
